### ISSUE TITLE
Environment variable error

### ISSUE THREAD

**Issue by KIRA009** [sharmaaditya570191/BossY#10] opened 2019-12-01 16:25 UTC
Getting this error when running `npm i`

```
ERROR in ./browser/index.js
Module build failed: Error: Using `babel-preset-react-app` requires that you specify `NODE_ENV` or `BABEL_ENV` environment variables. Valid values are "development", "test", and "production". Instead, received: undefined. (While processing preset: "/home/shohan/Desktop/node_modules/babel-preset-react-app/index.js")
```

It is an environment variable issue. Maybe something to do with the `babel-preset-react-app` version

If it is not, and environment variables need to be set manually, please mention them in the README

**Comment by sharmaaditya570191** [comment] 2019-12-02 05:54
Hey @KIRA009 try deleting your `node_modules` folder and running `sudo npm install` again. I could not reproduce the error you got on my machine hence closing this for now. Feel free to reopen this again if you have any doubts.

**Closed by sharmaaditya570191** 2019-12-02 05:54 UTC

**Comment by KIRA009** [comment] 2019-12-02 09:16
Just for anyone who comes across this issue. 

I was still having the issue, even after deleting the `node_modules` and reinstalling them. But the `npm start` command is working fine, even with all the errors during installation
